version: 2.1
orbs:
  terraform: 'circleci/terraform@dev:alpha'
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          # context: terraform
      - terraform/validate:
          checkout: true
          # context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          # context: terraform
          var_file: variables.tfvars
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            -terraform/plan
      - terraform/apply:
          attach-workspace: true
          # context: terraform
          var_file: variables.tfvars
          filters:
            branches:
              only: master
          requires:
            - hold-apply
